controller_list:

  - name: /neck
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - neck_shoulder_pan_joint
      - neck_shoulder_lift_joint
      - neck_elbow_joint
      - neck_wrist_1_joint
      - neck_wrist_2_joint
      - neck_wrist_3_joint
      - neck_joint_end
      - head1
      - head2
      - head3

